### PR TITLE
Fix non english characters mz tab item

### LINKED ISSUE #270: Add support for non-english characters in mz-tab-item label property
## Expected Behavior
When using non-english characters in label property all functionality should work same as with english characters

## Current Behavior
Exception "Syntax error, unrecognized expression: #%D0%B1%D0%B8%D0%B7%D0%BD%D0%B5%D1%81%D1%81-%D0%BC%D0%BE%D0%B4%D0%B5%D0%BB%D1%8C" occurs

## Possible Solution
Maybe it is something to do with encoding. My Angular app uses UTF-8.

## Steps to Reproduce (for bugs)
1. Create basic tab structure
2. Use non-english characters in mz-tab-item label property("Таб 1", "Таб 2", "Таб 3")
3. Load app, notice exception thrown already
4. Try to change tabs

## Your Environment
* Version used: 1.8.0-beta.0
* Angular version used: 5.2.0
* Browser Name and version: Chrome, latest version
* Operating System and version (desktop or mobile): Windows 10 16299

### PR DESCRIPTION
**Pull request by scote**
Fixed #270

### CODE REVIEW

File: src/app/tab/tab-item/tab-item.component.ts [hunk 1]
```diff
@@ -17,13 +17,14 @@ export class MzTabItemComponent {
...
+  @Input() label: string;
+  @Input() tabItemId: string
   @Input() target: string;
 
   tabs: HTMLElement;
   liElement: HTMLElement;
 
   get link(): string {
-    return this.label.replace(/\s+/g, '-').toLowerCase();
+    return this.tabItemId ? this.tabItemId : this.label.replace(/[^a-zA-Z0-9]/g, '').toLowerCase();
```
Comment (jfcere) [inline src/app/tab/tab-item/tab-item.component.ts]: No test to validate the regex with non english characters?

File: src/app/tab/tab.component.view.spec.ts [hunk 2]
```diff
@@ -116,19 +116,35 @@ describe('MzTabComponent:view', () => {
...
+        <mz-tab>
+          <mz-tab-item [label]="'lбabбel'">content</mz-tab-item>
+        </mz-tab>
+      `).then((fixture) => {
+
+        nativeElement = fixture.nativeElement;
+        fixture.detectChanges();
+
+        expect(tabItems()[0].querySelector('a').getAttribute('href')).toBe('#label');
+        // expect(tabContent()[0].getAttribute('id')).toBe('label');
```
Comment (jfcere) [inline src/app/tab/tab.component.view.spec.ts]: remove comment

File: src/app/tab/tab.component.view.spec.ts [hunk 3]
```diff
@@ -116,19 +116,35 @@ describe('MzTabComponent:view', () => {
...
+          <mz-tab-item [tabItemId]="'tabItemId'" [label]="'label'">content</mz-tab-item>
         </mz-tab>
       `).then((fixture) => {
 
         nativeElement = fixture.nativeElement;
         fixture.detectChanges();
 
         expect(tabItems()[0].querySelector('a').getAttribute('href')).toBe('#tabItemId');
-        expect(tabContent()[0].getAttribute('id')).toBe('tabItemId');
+        // expect(tabContent()[0].getAttribute('id')).toBe('tabItemId');
```
Comment (jfcere) [inline src/app/tab/tab.component.view.spec.ts]: remove comment
